config/routes.rb
Rails.application.routes.draw do
	devise_for :users, controllers: {
			sessions: 			'users/sessions',
			registrations: 	'users/registrations',
			passwords: 			'users/passwords',
      confirmations: 	'users/confirmations',
	}

	# resources :users

	# resources :sessions, only: [:new, :create, :destroy]
	# get 'login', to: 'sessions#new', as: 'login'
	# get 'logout', to: 'sessions#destroy', as: 'logout'
	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

	root 'home#index', as: 'home'

	get 'dashboard' => 'home#dashboard', as: 'dashboard'

	get '/flights/list' => 'flights#list', as: 'flights_list'

	resources :flights do
		resources :tickets
  end


	get '/flights/:id/seats' => 'flights#seats', as: 'flight_seats'
	get '/flights/:id/basic-info' => 'flights#basic_info', as: 'flights_basic_info'
	get '/flights/:id/passengers' => 'flights#passengers', as: 'flights_passengers'

	get '/passengers/autocomplete' => 'passengers#autocomplete', as: 'passengers_autocomplete'
	get '/airports/autocomplete' => 'airports#autocomplete', as: 'airports_autocomplete'
	get '/airlines/autocomplete' => 'airlines#autocomplete', as: 'airlines_autocomplete'

end

app/models/flight.rb
class Flight < ApplicationRecord

	self.per_page = 10

	before_save :default_values
	def default_values
		self.status ||= Flight.statuses[:ready_to_book]
	end

	# Relationships

	belongs_to :src_airport, class_name: 'Airport', foreign_key: 'src_airport_id'
	belongs_to :dst_airport, class_name: 'Airport', foreign_key: 'dst_airport_id'
	has_many :tickets
	has_many :passengers, through: :tickets

	# Validate

	validate :validate_airports
	validates :src_airport_id, presence: true
	validates :dst_airport_id, presence: true
	validates :price, presence: true, numericality: { greater_than: 0, less_than: 10000 }
	validates :capacity, presence: true, numericality: { greater_than: 10, less_than: 350 }
	validates_datetime :departure_at, :before => :arrival_at 
	validates_datetime :arrival_at, :after => :departure_at


	private def validate_airports
		errors.add(:src_airport_id, "Invalid") unless Airport.exists?(self.src_airport_id)
		errors.add(:dst_airport_id, "Invalid") unless Airport.exists?(self.dst_airport_id)
		errors.add(:src_airport_id, "and destination ariport can't be the same") unless self.src_airport_id != self.dst_airport_id
	end

	# Status

	enum status: {
		ready_to_book: 'ready_to_book',
		boarding: 'boarding',
		taking_off: 'taking_off',
		in_air: 'in_air',
		landing: 'landing',
		waiting: 'waiting',
	}

	def statusBadge
		@label = '<span class="badge badge-' + self.statusColor + '">' + Flight.human_enum_name(:status, self.status) + '</span>'
	end

	def statusColor
		case self.status
		when Flight.statuses[:ready_to_book]
			@color = "primary"
		when Flight.statuses[:boarding]
			@color = "warning"
		when Flight.statuses[:taking_off]
			@color = "warning"
		when Flight.statuses[:in_air]
			@color = "success"
		when Flight.statuses[:landing]
			@color = "warning"
		when Flight.statuses[:waiting]
			@color = "default"
		end
	end

	#

	def allSeats
		@seats = {}
		for i in 0..(self.capacity/6-1)
			for j in 0..5
				@seat = (i+1).to_s + "ABCDEF"[j].to_s
				@seats[@seat] = @seat
			end
		end
		if ((self.capacity - (i+1)*6-1) > 0)
			for j in 0..(self.capacity - (i+1)*6-1)
				@seat = (i+1).to_s + "ABCDEF"[j].to_s
				@seats[@seat] = @seat
			end 
		end
		return @seats
	end

	def availableSeats
		@seats = {}
		@tickets = self.tickets.pluck(:seat)
		for i in 0..(self.capacity/6-1)
			for j in 0..5
				@seat = (i+1).to_s + "ABCDEF"[j].to_s
				unless @tickets.include?(@seat) 
					@seats[@seat] = @seat
				end
			end
		end
		if ((self.capacity - (i+1)*6-1) > 0)
			for j in 0..(self.capacity - (i+1)*6-1)
				@seat = (i+1).to_s + "ABCDEF"[j].to_s
				unless @tickets.include?(@seat) 
					@seats[@seat] = @seat
				end
			end 
		end
		return @seats
	end

	def self.pagination(params, user) 
		paginate(:page => params[:page]).where(airline_id: user.airline_id).order('departure_at DESC')
	end

end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController

	def index
		@flights = Flight.pagination(params, current_user)

		@airports = Airport.limit(50).all

		# return view in JSON
		with_format :html do
	    	@view = render_to_string :partial => 'flights/index', :locals => { flights: @flights, airports: @airports}
		end
		render :json => { 
			:status => true,
			:view 	=> @view,
			:title	=> t(:flights)
		}
	end

	def list
		@flights = Flight.pagination(params, current_user)

		# return view in JSON
		with_format :html do
	    	@view = render_to_string :partial => 'flights/list', :locals => { flights: @flights}
		end
		render :json => { 
			:status => true,
			:view 	=> @view,
		}
	end

	def show
		@flight = Flight.find(params[:id])

		if @flight.airline_id != current_user.airline_id
			abort "Not allowed"
		end

		@tickets = @flight.tickets

		# return view in JSON
		with_format :html do
	    	@view = render_to_string :partial => 'flights/show', :locals => { flight: @flight, tickets: @tickets}
		end
		render :json => { 
			:status => true,
			:view 	=> @view,
			:title	=> t(:flight_id, id: @flight.id)
		}
	end

	def create
		@flight = current_user.airline.flights.new(flight_params(true))
		if (@flight.save)
			render :json => {
				:status => true
			}
		else
			# return view in JSON
			with_format :html do
		    	@view = render_to_string :partial => 'partials/messages', :locals => { errors: @flight.errors}
			end
			render :json => {
				:status => false,
				:errors => @view
			}
		end
	end

	def basic_info
		@flight = Flight.find(params[:id])

		if @flight.airline_id != current_user.airline_id
			abort "Not allowed"
		end

		# return view in JSON
		with_format :html do
	    	@view = render_to_string :partial => 'flights/basic_info', :locals => { flight: @flight}
		end
		render :json => {
			:status => true,
			:view 	=> @view
		}
	end

	def passengers
		@flight = Flight.find(params[:id])

		if @flight.airline_id != current_user.airline_id
			abort "Not allowed"
		end

		with_format :html do
	    	@view = render_to_string :partial => 'flights/passengers', :locals => { flight: @flight, tickets: @flight.tickets, seats: @flight.availableSeats}
		end
		render :json => {
			:status => true,
			:view 	=> @view
		}
	end

	def seats
		@flight = Flight.find(params[:id])

		if @flight.airline_id != current_user.airline_id
			abort "Not allowed"
		end

		render :json => {
			:status => true,
			:options => @flight.availableSeats.collect.collect{ |a| {
				id: a[0],
				text: a[0]
			}}
		}
	end

	def edit
		@flight = Flight.find(params[:id])

		if @flight.airline_id != current_user.airline_id
			abort "Not allowed"
		end

		@airports = Airport.limit(50).all.to_a
		# abort @airports.inspect
		# @airports << [@flight.src_airport, @flight.dst_airport]
		@airports.push(@flight.src_airport)
		@airports.push(@flight.dst_airport)

		# return view in JSON
		with_format :html do
	    	@view = render_to_string :partial => 'flights/edit', :locals => { flight: @flight, airports: @airports}
		end
		render :json => { 
			:status => true,
			:view 	=> @view,
		}
	end

	def update
		@flight = Flight.find(params[:id])

		if @flight.airline_id != current_user.airline_id
			abort "Not allowed"
		end

		if (@flight.update(flight_params(false)))
			render :json => {
				:status => true
			}
		else
			# return view in JSON
			with_format :html do
		    	@view = render_to_string :partial => 'partials/messages', :locals => { errors: @flight.errors}
			end
			render :json => {
				:status => false,
				:errors => @view
			}
		end
	end

	def destroy
		@flight = Flight.find(params[:id])

		if @flight.airline_id != current_user.airline_id
			abort "Not allowed"
		end

		if (@flight.tickets.count > 0)
			render :json => { :status => false }
		else
			@flight.destroy
			render :json => { :status => true }
		end
	end

	private def flight_params(create)
		if (create)
			params.require(:flight).permit(:src_airport_id, :dst_airport_id, :arrival_at, :departure_at, :price, :capacity)
		else
			params.require(:flight).permit(:src_airport_id, :dst_airport_id, :arrival_at, :departure_at, :price)
		end
	end

end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/flights/_basic_info.html.erb
<div class="card user-info-list card be-loading" id="BasicFlightInfo">
  <div class="card-header card-header-divider">
    <%= t :basic_info %>
    <div class="tools dropdown">
      <span class="icon mdi mdi-edit" id="EditFlightBtn" data-href="<%= url_for edit_flight_path(flight) %>"></span>
    </div>
  </div>
  <div class="card-body">
    <table class="no-border no-strip skills">
      <tbody class="no-border-x no-border-y">
        <tr>
          <td class="icon"><span class="mdi mdi-pin"></span></td>
          <td class="item"><%= t :src_airport %><span class="icon s7-portfolio"></span></td>
          <td><%= flight.src_airport.name %></td>
        </tr>
        <tr>
          <td class="icon"><span class="mdi mdi-pin"></span></td>
          <td class="item"><%= t :dst_airport %><span class="icon s7-gift"></span></td>
          <td><%= flight.dst_airport.name %></td>
        </tr>
        <tr>
          <td class="icon"><span class="mdi mdi-alarm"></span></td>
          <td class="item"><%= t :departure_at %><span class="icon s7-phone"></span></td>
          <td><%= flight.departure_at.strftime('%Y-%m-%d %H:%M') %></td>
        </tr>
        <tr>
          <td class="icon"><span class="mdi mdi-alarm"></span></td>
          <td class="item"><%= t :arrival_at %><span class="icon s7-map-marker"></span></td>
          <td><%= flight.arrival_at.strftime('%Y-%m-%d %H:%M') %></td>
        </tr>
        <tr>
          <td class="icon"><span class="mdi mdi-accounts"></span></td>
          <td class="item"><%= t :capacity %><span class="icon s7-global"></span></td>
          <td><%= flight.capacity %></td>
        </tr>
        <tr>
          <td class="icon"><span class="mdi mdi-money"></span></td>
          <td class="item"><%= t :price %><span class="icon s7-global"></span></td>
          <td><%= flight.price %>&euro;</td>
        </tr>
      </tbody>
    </table>
  </div>
  <div class="be-spinner">
    <svg width="40px" height="40px" viewBox="0 0 66 66" xmlns="http://-www.w3.org/2000/svg">
      <circle class="circle" fill="none" stroke-width="4" stroke-linecap="round" cx="33" cy="33" r="30"></circle>
    </svg>
  </div>
</div>

app/views/flights/_edit.html.erb
<div class="card card-border be-loading" id="BasicFlightInfo">
	<%= form_for(:flight, url: flight_path(flight), method: :patch, :html => { 'data-redirect' => url_for(flights_basic_info_path(flight)) }) do |f| %>
        <div class="card-header card-header-divider">
          <%= t :basic_info %>
          <div class="tools dropdown">
          	<button class="btn btn-danger mr-5" id="CancelEditBtn"><%= t :close %></button>
			<%= f.submit({:class => 'btn btn-primary'}) %>
          </div>
        </div>
		<div class="card-body">
			<div class="row">
				<div class="col-6">
					<div class="form-group">
						<%= f.label(:src_ariport_id) %> 
						<%= f.select(:src_airport_id, airports.collect {|a| [a.name, a.id]}, {}, { class: 'select2' })%>
					</div>
				</div>
				<div class="col-6">
					<div class="form-group">
						<%= f.label(:dst_airport_id) %>
						<%= f.select(:dst_airport_id, airports.collect {|a| [a.name, a.id]}, {}, { class: 'select2' }) %>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-6">
					<div class="form-group">
						<%= f.label :departure_at %>
						<%= f.text_field(:departure_at, { :value => flight.departure_at.strftime('%Y-%m-%d %H:%M'), :class => 'form-control', :id => 'departure_at', :autocomplete => 'off' }) %>
					</div>
				</div>
				<div class="col-6">
					<div class="form-group">
						<%= f.label :arrival_at %>
						<%= f.text_field(:arrival_at, { :value => flight.arrival_at.strftime('%Y-%m-%d %H:%M'), :class => 'form-control', :id => 'arrival_at', :autocomplete => 'off' }) %>
					</div>
				</div>
			</div>

			<div class="row">
				<div class="col-6">
					<div class="form-group">
						<%= f.label :price %>
						<%= f.text_field(:price, { :class => 'form-control', :id => 'price' }) %>
					</div>
				</div>
				<div class="col-6">
					<div class="form-group">
						<%= f.label :capacity %>
						<%= f.text_field(:capacity, { :class => 'form-control', :id => 'capacity', disabled: 'true' }) %>
					</div>
				</div>
			</div>
		</div>
		
		<div class="be-spinner">
		  	<svg width="40px" height="40px" viewBox="0 0 66 66" xmlns="http://-www.w3.org/2000/svg">
		  		<circle class="circle" fill="none" stroke-width="4" stroke-linecap="round" cx="33" cy="33" r="30"></circle>
		  	</svg>
	 	</div>
	<% end %>
</div>

app/views/flights/_index.html.erb
<div class="main-content container-fluid be-loading" id="main-content">

	<div class="be-spinner">
		<svg width="40px" height="40px" viewBox="0 0 66 66" xmlns="http://-www.w3.org/2000/svg">
			<circle class="circle" fill="none" stroke-width="4" stroke-linecap="round" cx="33" cy="33" r="30"></circle>
		</svg>
	</div>

	<%= render partial: 'flights/new', locals: { airports: airports } %>

	<div class="modal fade" id="DeleteFlightModal" tabindex="-1" role="dialog">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button class="close" type="button" data-dismiss="modal" aria-hidden="true"><span class="mdi mdi-close"></span></button>
          </div>
          <div class="modal-body">
            <div class="text-center">
              <div class="text-danger"><span class="modal-main-icon mdi mdi-close-circle-o"></span></div>
              <h3>Danger!</h3>
              <p>Are you sure you want to remove the flight?</p>
              <div class="mt-8">
                <button class="btn btn-space btn-secondary" id="CancelBtn" type="button" data-dismiss="modal"><%= t :cancel %></button>
                <button class="btn btn-space btn-danger" id="ConfirmBtn" type="button" data-dismiss="modal"><%= t :proceed %></button>
              </div>
            </div>
          </div>
          <div class="modal-footer"></div>
        </div>
      </div>
    </div>

    <div class="modal fade" id="DeleteFlightErrorModal" tabindex="-1" role="dialog">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button class="close" type="button" data-dismiss="modal" aria-hidden="true"><span class="mdi mdi-close"></span></button>
          </div>
          <div class="modal-body">
            <div class="text-center">
              <div class="text-danger"><span class="modal-main-icon mdi mdi-close-circle-o"></span></div>
              <h3>Danger!</h3>
              <p>You can't delete a flight which has passenger!</p>
              <div class="mt-8">
                <button class="btn btn-space btn-danger" type="button" data-dismiss="modal"><%= t :proceed %></button>
              </div>
            </div>
          </div>
          <div class="modal-footer"></div>
        </div>
      </div>
    </div>

	<div class="row">
		<div class="col-12">
			<div class="row mb-10">
				<div class="col-12">
					<button class="btn btn-primary float-right" data-toggle="modal" data-target="#NewFlightModal"><i class="mdi mdi-plus"></i> <%= t(:new) %></button>
				</div>
			</div>

			<%= render partial: 'flights/list', locals: { flights: flights } %>
		</div>
	</div>

	<script type="text/javascript">
	    $('#arrival_at, #departure_at').datetimepicker();

		AppRails.loadView('<%= url_for flights_list_path %>', '#FlightList');
	</script>
</div>

app/views/flights/_list.html.erb
<div class="card card-table be-loading" id="FlightList">
    <div class="card-header">Basic Tables</div>
    <div class="card-body">
		<table class="table table-striped" id="FlightsTable">
			<thead>
				<tr>
					<th style=""><%= t :flightid %></th>
					<th style=""><%= t :src_airport %></th>
					<th style=""><%= t :dst_airport %></th>
					<th style=""><%= t :departure_at %></th>
					<th style=""><%= t :arrival_at %></th>
					<th style=""><%= t :status %></th>
					<th class="actions"></th>
				</tr>
			</thead>
			<tbody>
				<% flights.each do |flight| %>
					<tr>
						<td><%= flight.id %></td>
						<td><%= flight.src_airport.name %></td>
						<td><%= flight.dst_airport.name %></td>
						<td><%= flight.departure_at.strftime('%Y-%m-%d %H:%M') %></td>
						<td><%= flight.arrival_at.strftime('%Y-%m-%d %H:%M') %></td>
						<td><%= flight.statusBadge.html_safe %></td>
						<td class="actions">
							<a href="javascript: void(0)" class="btn btn-primary show-flight" data-href="<%= url_for flight_path(flight) %>"><%= t(:view) %></a>
							<a href="javascript: void(0)" class="btn btn-danger delete-flight" data-href="<%= url_for flight_path(flight) %>"><%= t(:delete) %></a>
						</td>
					</tr>
				<% end %>
			</tbody>
		</table>
		<%= will_paginate flights %>
    </div>
	</div>
</div>

app/views/flights/_new.html.erb
<!-- NEW FLIGHT MODAL -->
<div class="modal fade colored-header colored-header-primary show" id="NewFlightModal" role="dialog">
	<div class="modal-dialog">
		<%= form_for(:flight, url: flights_path) do |f| %>
			<div class="modal-content be-loading">
				<div class="modal-header modal-header-colored">
					<h3 class="modal-title"><%= t(:new_flight) %></h3>
					<button class="close md-close" type="button" data-dismiss="modal" aria-hidden="true">
						<span class="mdi mdi-close"></span>
					</button>
				</div>
				<div class="modal-body">
					<div class="row">
						<div class="col-6">
							<div class="form-group">
								<%= f.label(:src_ariport_id) %> 
								<%= f.select(:src_airport_id, airports.collect {|a| [a.name, a.id]}, {}, { class: 'select2' })%>
							</div>
						</div>
						<div class="col-6">
							<div class="form-group">
								<%= f.label(:dst_airport_id) %>
								<%= f.select(:dst_airport_id, airports.collect {|a| [a.name, a.id]}, {}, { class: 'select2' }) %>
							</div>
						</div>
					</div>
					<div class="row">
						<div class="col-6">
							<div class="form-group">
								<%= f.label :departure_at %>
								<%= f.text_field(:departure_at, { :class => 'form-control', :id => 'departure_at', :autocomplete => 'off' }) %>
							</div>
						</div>
						<div class="col-6">
							<div class="form-group">
								<%= f.label :arrival_at %>
								<%= f.text_field(:arrival_at, { :class => 'form-control', :id => 'arrival_at', :autocomplete => 'off' }) %>
							</div>
						</div>
					</div>

					<div class="row">
						<div class="col-6">
							<div class="form-group">
								<%= f.label :price %>
								<%= f.text_field(:price, { :class => 'form-control', :id => 'price' }) %>
							</div>
						</div>
						<div class="col-6">
							<div class="form-group">
								<%= f.label :capacity %>
								<%= f.text_field(:capacity, { :class => 'form-control', :id => 'capacity' }) %>
								<span class="text-muted text-small">This value can't be changed later.</span>
							</div>
						</div>
					</div>
				</div>
				<div class="modal-footer">
					<button class="btn btn-secondary md-close" type="button" data-dismiss="modal">Cancel</button>
					<%= f.submit({:class => 'btn btn-primary'}) %>
				</div>
				<div class="be-spinner">
					<svg width="40px" height="40px" viewBox="0 0 66 66" xmlns="http://-www.w3.org/2000/svg">
						<circle class="circle" fill="none" stroke-width="4" stroke-linecap="round" cx="33" cy="33" r="30"></circle>
					</svg>
				</div>
			</div>
		<% end %>
	</div>
</div>

app/views/flights/_passengers.html.erb
<div class="card card-border be-loading" id="PassengersCard">
	<div class="card-header card-header-divider">
	    <%= t :passengers %>
	    <div class="tools dropdown">
	    	<span class="icon mdi mdi-plus" id="NewPassengerBtn" data-toggle="modal" data-target="#NewPassengerModal"></span>
	    </div>
	</div>
	<div class="card-body">
		<div class="plane">
			<div class="plane-head"></div>
			<div class="plane-body">
				<% for i in 0..(flight.capacity / 6-1) %>
					<div class="plane-row">
						<% for j in 0..5 %>
							<% @seat = (i+1).to_s + "ABCDEF"[j].to_s %>
							<div 
								class="plane-seat <%= tickets.pluck(:seat).include?(@seat) ? 'sold' : '' %>" 
								data-href="<%= tickets.pluck(:seat).include?(@seat) ? url_for(edit_flight_ticket_path(flight.id, tickets.select {|t| t.seat == @seat }.first.id)) : '' %>" 
								data-seat="<%= @seat %>"></div>
						<% end %>
						<div class="clearfix"></div>
					</div>
				<% end %>
				<div class="plane-row">
					<% if ((flight.capacity - (i+1)*6-1) > 0) %>
						<% for j in 0..(flight.capacity - (i+1)*6-1) %>
							<% @seat = (i+1).to_s + "ABCDEF"[j].to_s %>
							<div 
								class="plane-seat <%= tickets.pluck(:seat).include?(@seat) ? 'sold' : '' %>" 
								data-href="<%= tickets.pluck(:seat).include?(@seat) ? url_for(edit_flight_ticket_path(flight.id, tickets.select {|t| t.seat == @seat }.first.id)) : '' %>" 
								data-seat="<%= @seat %>"></div>
						<% end %>
					<% end %>
					<div class="clearfix"></div>
				</div>
			</div>
			<div class="plane-tail"></div>
		</div>
	</div>
</div>

app/views/flights/_show.html.erb
<div class="main-content container-fluid be-loading" id="main-content">

  <%= render partial: 'tickets/new', locals: { flight: flight, tickets: tickets, seats: flight.availableSeats } %>

  <div class="modal fade colored-header colored-header-primary" id="EditPassengerModal" tabindex="-1" role="dialog">
    <div class="modal-dialog">
      <div class="modal-content be-loading">
        <div class="be-spinner">
          <svg width="40px" height="40px" viewBox="0 0 66 66" xmlns="http://-www.w3.org/2000/svg">
            <circle class="circle" fill="none" stroke-width="4" stroke-linecap="round" cx="33" cy="33" r="30"></circle>
          </svg>
        </div>
      </div>
    </div>
  </div>

  <div class="modal fade" id="DeleteTicketModal" tabindex="-1" role="dialog">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button class="close" type="button" data-dismiss="modal" aria-hidden="true"><span class="mdi mdi-close"></span></button>
          </div>
          <div class="modal-body">
            <div class="text-center">
              <div class="text-danger"><span class="modal-main-icon mdi mdi-close-circle-o"></span></div>
              <h3>Danger!</h3>
              <p>Are you sure you want to remove the passenger?</p>
              <div class="mt-8">
                <button class="btn btn-space btn-secondary" id="CancelBtn" type="button" data-dismiss="modal"><%= t :cancel %></button>
                <button class="btn btn-space btn-danger" id="ConfirmBtn" type="button" data-dismiss="modal"><%= t :proceed %></button>
              </div>
            </div>
          </div>
          <div class="modal-footer"></div>
        </div>
      </div>
    </div>

	<div class="row">
		<div class="col-md-6 col-sm-12">
      <%= render partial: 'flights/basic_info', locals: { flight: flight } %>
		</div>
    <div class="col-md-6 col-sm-12">
      <%= render partial: 'flights/passengers', locals: { flight: flight, tickets: tickets } %>
    </div>
	</div>


  <div class="be-spinner">
  	<svg width="40px" height="40px" viewBox="0 0 66 66" xmlns="http://-www.w3.org/2000/svg">
  		<circle class="circle" fill="none" stroke-width="4" stroke-linecap="round" cx="33" cy="33" r="30"></circle>
  	</svg>
  </div>
</div>