config/routes.rb
Rails.application.routes.draw do
	devise_for :users, controllers: {
			sessions: 			'users/sessions',
			registrations: 	'users/registrations',
			passwords: 			'users/passwords',
      confirmations: 	'users/confirmations',
	}

	# resources :users

	# resources :sessions, only: [:new, :create, :destroy]
	# get 'login', to: 'sessions#new', as: 'login'
	# get 'logout', to: 'sessions#destroy', as: 'logout'
	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

	root 'home#index', as: 'home'

	get 'dashboard' => 'home#dashboard', as: 'dashboard'

	get '/flights/list' => 'flights#list', as: 'flights_list'

	resources :flights do
		resources :tickets
  end


	get '/flights/:id/seats' => 'flights#seats', as: 'flight_seats'
	get '/flights/:id/basic-info' => 'flights#basic_info', as: 'flights_basic_info'
	get '/flights/:id/passengers' => 'flights#passengers', as: 'flights_passengers'

	get '/passengers/autocomplete' => 'passengers#autocomplete', as: 'passengers_autocomplete'
	get '/airports/autocomplete' => 'airports#autocomplete', as: 'airports_autocomplete'
	get '/airlines/autocomplete' => 'airlines#autocomplete', as: 'airlines_autocomplete'

end

app/models/ticket.rb
class Ticket < ApplicationRecord
	belongs_to :passenger
	belongs_to :flight

	validates :passenger_id, presence: true
	validate :validate_passenger
	validates :seat, presence: true
	validate :validate_seat

	private def validate_passenger
		if self.new_record?
			errors.add(:passenger_id, "already has a ticket for this flight.") unless Ticket.where(flight_id: self.flight_id).where(passenger_id: self.passenger_id).count == 0
		else
			errors.add(:passenger_id, "already has a ticket for this flight.") unless Ticket.where(flight_id: self.flight_id).where(passenger_id: self.passenger_id).where.not(id: self.id).count == 0
		end
	end

	private def validate_seat
		if self.new_record?
			errors.add(:seat, "is already taken on this flight") unless Ticket.where(flight_id: self.flight_id).where(seat: self.seat).count() == 0
		else
			errors.add(:seat, "is already taken on this flight") unless Ticket.where(flight_id: self.flight_id).where(seat: self.seat).where.not(id: self.id).count() == 0
		end		

		# seat exists
		errors.add(:seat, "doesn't exist on this flight") unless self.flight.allSeats.include?(self.seat)
	end	

end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController

	include ApplicationHelper

	def new

	end

	def create
		@flight = Flight.find(params[:flight_id])

		if @flight.airline_id != current_user.airline_id
			abort "Not allowed"
		end

		@ticket = @flight.tickets.new(ticket_params)

		if (@ticket.save)
			render :json => { :status => true }
		else
			with_format :html do
		    	@view = render_to_string :partial => 'partials/messages', :locals => { errors: @ticket.errors}
			end
			render :json => {
				:status => false,
				:errors => @view
			}
		end
	end

	def edit 
		@flight = Flight.find(params[:flight_id])

		if @flight.airline_id != current_user.airline_id
			abort "Not allowed"
		end

		@ticket = Ticket.find(params[:id])
		@seats = @flight.availableSeats
		@seats[@ticket.seat] = @ticket.seat;

		with_format :html do
	    	@view = render_to_string :partial => 'tickets/edit', :locals => { 
	    		flight: @flight, 
	    		ticket: @ticket,
	    		tickets: @flight.tickets, 
	    		seats: @seats
	    	}
		end
		render :json => {
			:status => true,
			:view 	=> @view
		}
	end

	def update
		@flight = Flight.find(params[:flight_id])

		if @flight.airline_id != current_user.airline_id
			abort "Not allowed"
		end

		@ticket = Ticket.find(params[:id])

		if (@ticket.update(ticket_params))
			render :json => { :status => true }
		else
			with_format :html do
		    	@view = render_to_string :partial => 'partials/messages', :locals => { errors: @ticket.errors}
			end
			render :json => {
				:status => false,
				:errors => @view
			}
		end
	end

	def destroy
		@flight = Flight.find(params[:flight_id])

		if @flight.airline_id != current_user.airline_id
			abort "Not allowed"
		end

		@ticket = Ticket.find(params[:id])
		@ticket.destroy

		render :json => { :status => true }
	end

	private def ticket_params
		params.require(:ticket).permit(:passenger_id, :seat)
	end
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/tickets/_edit.html.erb
<div class="modal fade colored-header colored-header-primary show" id="EditPassengerModal" role="dialog">
	<div class="modal-dialog">
		<%= form_for(:ticket, url: flight_ticket_path(flight, ticket), method: :patch, :html => { 'data-redirect' => url_for(flights_passengers_path(flight)) }) do |f| %>
			<div class="modal-content be-loading">
				<div class="modal-header modal-header-colored">
					<h3 class="modal-title"><%= t(:new_passenger) %></h3>
					<button class="close md-close" type="button" data-dismiss="modal" aria-hidden="true">
						<span class="mdi mdi-close"></span>
					</button>
				</div>
				<div class="modal-body">
					<div class="row">
						<div class="col-12">
							<div class="form-group">
								<%= f.label(:passenger) %> 
								<%= f.text_field(:passenger_name, { value: ticket.passenger.fullname(), class: 'form-control', id: 'passenger_name', 'data-href': url_for(passengers_autocomplete_path) })%>
								<%= f.hidden_field(:passenger_id, { value: ticket.passenger_id }) %>
								<%= f.hidden_field(:flight_id, { class: 'permanent', value: flight.id }) %>
								<span class="text-muted text-small">Autocomplete by passenger full name.</span>
							</div>
						</div>
					</div>
					<div class="row">
						<div class="col-12">
							<div class="form-group">
								<%= f.label(:seat) %>
								<%= f.select(:seat, seats, {}, { value: ticket.seat, class: 'select2', id: 'seat' }) %>
							</div>
						</div>
					</div>
				</div>
				<div class="modal-footer">
					<button class="btn btn-danger" id="DeleteBtn" type="button" data-dismiss="modal" data-href="<%= url_for flight_ticket_path(flight) %>"><%= t :delete %></button>
					<%= f.submit({:class => 'btn btn-primary'}) %>
				</div>
				<div class="be-spinner">
					<svg width="40px" height="40px" viewBox="0 0 66 66" xmlns="http://-www.w3.org/2000/svg">
						<circle class="circle" fill="none" stroke-width="4" stroke-linecap="round" cx="33" cy="33" r="30"></circle>
					</svg>
				</div>
			</div>
		<% end %>
	</div>
</div>

app/views/tickets/_new.html.erb
<!-- NEW FLIGHT MODAL -->
<div class="modal fade colored-header colored-header-primary" id="NewPassengerModal" role="dialog">
	<div class="modal-dialog">
		<%= form_for(:ticket, url: flight_tickets_path(flight), :html => { 
			'data-redirect' => url_for(flights_passengers_path(flight)), 
			'data-select2' => url_for(flight_seats_path(flight)), 
		}) do |f| %>
			<div class="modal-content be-loading">
				<div class="modal-header modal-header-colored">
					<h3 class="modal-title"><%= t(:new_passenger) %></h3>
					<button class="close md-close" type="button" data-dismiss="modal" aria-hidden="true">
						<span class="mdi mdi-close"></span>
					</button>
				</div>
				<div class="modal-body">
					<div class="row">
						<div class="col-12">
							<div class="form-group">
								<%= f.label(:passenger) %> 
								<%= f.text_field(:passenger_name, { class: 'form-control', id: 'passenger_name', 'data-href': url_for(passengers_autocomplete_path) })%>
								<%= f.hidden_field(:passenger_id) %>
								<%= f.hidden_field(:flight_id, { class: 'permanent', value: flight.id }) %>
								<span class="text-muted text-small">Autocomplete by passenger full name.</span>
							</div>
						</div>
					</div>
					<div class="row">
						<div class="col-12">
							<div class="form-group">
								<%= f.label(:seat) %>
								<%= f.select(:seat, seats, {}, { class: 'select2', id: 'seat' }) %>
							</div>
						</div>
					</div>
				</div>
				<div class="modal-footer">
					<button class="btn btn-secondary md-close" type="button" data-dismiss="modal">Cancel</button>
					<%= f.submit({:class => 'btn btn-primary'}) %>
				</div>
				<div class="be-spinner">
					<svg width="40px" height="40px" viewBox="0 0 66 66" xmlns="http://-www.w3.org/2000/svg">
						<circle class="circle" fill="none" stroke-width="4" stroke-linecap="round" cx="33" cy="33" r="30"></circle>
					</svg>
				</div>
			</div>
		<% end %>
	</div>
</div>