config/routes.rb
Rails.application.routes.draw do
	devise_for :users, controllers: {
			sessions: 			'users/sessions',
			registrations: 	'users/registrations',
			passwords: 			'users/passwords',
      confirmations: 	'users/confirmations',
	}

	# resources :users

	# resources :sessions, only: [:new, :create, :destroy]
	# get 'login', to: 'sessions#new', as: 'login'
	# get 'logout', to: 'sessions#destroy', as: 'logout'
	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

	root 'home#index', as: 'home'

	get 'dashboard' => 'home#dashboard', as: 'dashboard'

	get '/flights/list' => 'flights#list', as: 'flights_list'

	resources :flights do
		resources :tickets
  end


	get '/flights/:id/seats' => 'flights#seats', as: 'flight_seats'
	get '/flights/:id/basic-info' => 'flights#basic_info', as: 'flights_basic_info'
	get '/flights/:id/passengers' => 'flights#passengers', as: 'flights_passengers'

	get '/passengers/autocomplete' => 'passengers#autocomplete', as: 'passengers_autocomplete'
	get '/airports/autocomplete' => 'airports#autocomplete', as: 'airports_autocomplete'
	get '/airlines/autocomplete' => 'airlines#autocomplete', as: 'airlines_autocomplete'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- <link rel="shortcut icon" href="img/logo.gif"> -->
    <title></title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script type="text/javascript">
      var BASE_URL = '<%= request.base_url %>'
    </script>

    <%= javascript_include_tag 'application' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  
    <link href="//cdn.datatables.net/1.10.12/css/jquery.dataTables.min.css" rel="stylesheet" type="text/css" />


</head>
<body>

 <div class="be-wrapper">
    <nav class="navbar navbar-expand fixed-top be-top-header">
      <div class="container-fluid">
        <div class="be-navbar-header">
          <a class="navbar-brand" href="index.html">
            <i class="mdi mdi-airplane"></i> <%= t :APP_NAME %>
          </a>
        </div>
        <div class="be-right-navbar">
          <ul class="nav navbar-nav float-right be-user-nav">
            <li class="nav-item dropdown"><a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" role="button" aria-expanded="false"><img src="/img/avatar.png" alt="Avatar"><span class="user-name"><%= current_user.email %></span></a>
              <div class="dropdown-menu" role="menu">     
                <div class="user-info">
                  <div class="user-name"><%= current_user.email %></div>
                  <div class="user-position"><%= t :airline %>: <%= current_user.airline.name %></div>
                </div>
                <%#= link_to('Logout', destroy_user_session_path, method: :delete) %>
                <a class="dropdown-item" href="<%= url_for destroy_user_session_path %>" data-method="delete"><span class="icon mdi mdi-power"></span><%= t :logout %></a>
              </div>
            </li>
          </ul>
          <div class="page-title" id="page-title"><span></span></div>
        </div>
      </div>
    </nav>
    <div class="be-left-sidebar">
      <div class="left-sidebar-wrapper">
        <div class="left-sidebar-spacer">
          <div class="left-sidebar-scroll">
            <div class="left-sidebar-content">
              <ul class="sidebar-elements" id="main-menu">
                <li class="divider">Menu</li>
                <li>
                  <a href="javascript: void(0)" data-href="<%= url_for dashboard_path %>" data-load="ajax" data-view="#main-content">
                    <i class="icon mdi mdi-view-dashboard"></i>
                    <span><%= t(:dashboard) %></span>
                  </a>
                </li>
                <li>  
                  <a href="javascript: void(0)" data-href="<%= url_for flights_path %>" data-load="ajax" data-view="#main-content">
                    <i class="icon mdi mdi-home"></i>
                    <span><%= t(:flights) %></span>
                  </a>       
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="be-content">
      <div class="main-content container-fluid be-loading" id="main-content">
        <%= yield %>
      </div>
    </div>
  </div>
  <script type="text/javascript">
    $(document).ready(function() {
      $('ul#main-menu li:not(.divider)').first().addClass('active');
      AppRails.loadView('<%= url_for dashboard_path %>');
    });
  </script>
</body>
</html>

app/views/layouts/auth.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- <link rel="shortcut icon" href="img/logo.gif"> -->
    <title></title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_include_tag 'application' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>
  <body class="be-splash-screen">
    <div class="be-wrapper be-login">
      <div class="be-content">
        <div class="main-content container-fluid">
          <%= yield %>
        </div>
      </div>
    </div>
    <script type="text/javascript">
      $(document).ready(function(){
        //-initialize the javascript

      });
      
    </script>
  </body>
</html>